Traceback (most recent call last):
  File "slowloris.py", line 168, in <module>
    main()
  File "slowloris.py", line 165, in main
    run()
  File "slowloris.py", line 114, in run
    response = requests.get(URL)
  File "/home/maxkrivich/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/maxkrivich/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/maxkrivich/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/maxkrivich/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/maxkrivich/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0xb65ea24c>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
